name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]
  workflow_dispatch:
  
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Git checkout
      uses: actions/checkout@v4  

    - name: Test
      shell: pwsh
      run: Invoke-Pester